# Generated by Django 3.1.2 on 2020-11-07 21:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201107_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('genre', models.ManyToManyField(to='catalogo.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('E', 'En_envio'), ('R', 'Reservado'), ('D', 'Disponible'), ('M', 'Mantencion')], default='D', help_text='alimento_disponible', max_length=1)),
                ('alimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.alimento')),
            ],
            options={
                'ordering': ['alimento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Caduce')),
            ],
            options={
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.AddField(
            model_name='alimento',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto'),
        ),
    ]
