# Generated by Django 3.1.2 on 2020-11-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201107_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('E', 'En_envio'), ('R', 'Reservado'), ('D', 'Disponible'), ('M', 'Mantencion')], default='D', help_text='Alimento_Disponible', max_length=1),
        ),
    ]
