# Generated by Django 3.1.2 on 2020-11-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201107_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentoinstance',
            options={'ordering': ['alimen_dispo']},
        ),
        migrations.AddField(
            model_name='alimentoinstance',
            name='alimen_dispo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
