# Generated by Django 3.1.2 on 2020-11-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201113_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentoinstance',
            options={'ordering': ['alimento_disponible']},
        ),
        migrations.AddField(
            model_name='alimentoinstance',
            name='alimento_disponible',
            field=models.DateField(blank=True, null=True),
        ),
    ]
