# Generated by Django 3.1.2 on 2020-12-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20201209_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
