# Generated by Django 3.1.2 on 2020-12-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alimento_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='image',
            new_name='imagen',
        ),
    ]
